DROP TABLE IF EXISTS ad_lead_events CASCADE;
DROP TABLE IF EXISTS ad_liquidity_reports CASCADE;
DROP TABLE IF EXISTS ad_performance_daily CASCADE;
DROP TABLE IF EXISTS ads CASCADE;
DROP TABLE IF EXISTS ad_groups CASCADE;
DROP TABLE IF EXISTS ad_campaigns CASCADE;
DROP TABLE IF EXISTS ad_accounts CASCADE;